name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Set up NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
    - name: Build go-mobile library
      run: cd clients/go-mobile && ./create_archive.sh

    - name: Grant execute permission for gradlew
      run: cd clients/Android/ultrablue/ && chmod +x gradlew
    - name: Build with Gradle
      run: cd clients/Android/ultrablue/ && ./gradlew build
