# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build server
      run: cd server && go build -v ./...

    - name: Test server
      run: cd server && go test -v ./...

    - uses: actions/upload-artifact@v3
      with:
        name: ultrablue-server
        path: server/ultrablue-server

  testbed:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ 'debian', 'ubuntu' ]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Set up mkosi
      uses: systemd/mkosi@v14
    - name: Build testbed
      run: make -C server/testbed build DISTRIBUTION=${{ matrix.distribution }}

    - uses: actions/upload-artifact@v3
      with:
        name: ultrablue-testbed-${{ matrix.distribution }}
        path: |
          server/testbed/mkosi.output/${{ matrix.distribution }}*/
          !server/testbed/mkosi.output/${{ matrix.distribution }}*/*.cache-*
